export const DUMMY_DATA2 = [
	{
		firstName: 'Oscar',
		lastName: 'Cookson',
		emailAddress: 'oscarscookson@rhyta.com',
		imagePath: '../../assets/roommates/anonymous-person1.jpg',
		bio: 'I like pickles',
	},
	{
		firstName: 'Edward',
		lastName: 'Latham',
		emailAddress: 'edwardelatham@rhyta.com',
		imagePath: '../../assets/roommates/anonymous-person2.jpg',
		bio: 'I am friendly and quiet',
	},
	{
		firstName: 'Pauline',
		lastName: 'Font',
		emailAddress: 'paulinefont@rhyta.com',
		imagePath: '../../assets/roommates/anonymous-person3.jpg',
		bio: "I don't party so its quiet",
	},
	{
		firstName: 'Ana G.',
		lastName: 'Fields',
		emailAddress: 'anagfields@armyspy.com',
		imagePath: '../../assets/roommates/anonymous-person4.jpg',
		bio: 'Lets room together!',
	},
	{
		firstName: 'Charlotte',
		lastName: 'Skinner',
		emailAddress: 'charlotteskinner@dayrep.com',
		imagePath: '../../assets/roommates/anonymous-person5.jpg',
		bio: 'Hello I am a college student!',
	},
	{
		firstName: 'James',
		lastName: 'Sanders',
		emailAddress: 'jamesmsanders@jourrapide.com',
		imagePath: '../../assets/roommates/anonymous-person6.jpg',
		bio: 'Follow my youtube channel here: https://www.youtube.com/watch?v=dQw4w9WgXcQ',
	},
	{
		firstName: 'David',
		lastName: 'Gosha',
		emailAddress: 'davidagosha@dayrep.com',
		imagePath: '../../assets/roommates/anonymous-person7.jpg',
		bio: "I am pet friendly, let's room together!",
	},
	{
		firstName: 'Jana',
		lastName: 'Salazar',
		emailAddress: 'janajsalazar@rhyta.com',
		imagePath: '../../assets/roommates/anonymous-person8.jpg',
		bio: 'I am open to anything.',
	},
	{
		firstName: 'Luis',
		lastName: 'Sandell',
		emailAddress: 'luissandell@dayrep.com',
		imagePath: './../../assets/roommates/anonymous-person9.jpg',
		bio: 'Hello there, friend!',
	},
]
