const DUMMY_DATA2 = [
	{
		streetAddress: 'sunt, plaat7 amet pariatur, ani123123mi eveniet',
		price: 56555,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 30,
		peopleInterested: {},
	},
	{
		streetAddress: 'cupiate deiti labori8m x123123ime ducimus!',
		price: 66666,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 23,
		peopleInterested: {},
	},
	{
		streetAddress: 'Lorem ipsum dolor sit amet cons2ectetur adipisicing.',
		price: 11111,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 3,
		peopleInterested: {},
	},
	{
		streetAddress: 'at  acus cu9tate, atque sed per123123ferendis',
		price: 12232,
		bedrooms: 69,
		bathrooms: 69,
		zipCode: '69696',
		numPeopleInterested: 69,
		peopleInterested: {},
	},
	{
		streetAddress: 'siique sed fugiat hic ea 6a23123iam iure ',
		price: 44444,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 31,
		peopleInterested: {},
	},
	{
		streetAddress: 'ex velit mag3ni qui eum, corpor123 inventore ',
		price: 22222,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 32,
		peopleInterested: {},
	},
	{
		streetAddress: 'praeseium 5ipsam a libero, bditi23123s placeat ',
		price: 33333,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 20,
		peopleInterested: {},
	},
	{
		streetAddress: 'at  accuus cuptate, a3t sed pr12erendis',
		price: 77777,
		bedrooms: 69,
		bathrooms: 69,
		zipCode: '69696',
		numPeopleInterested: 69,
		peopleInterested: {},
	},
	{
		streetAddress: 'Lorem ipsum dolor sit a0met consetur adipisicing.',
		price: 88888,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 3,
		peopleInterested: {},
	},
	{
		streetAddress: 'ex velit magni qui eum, corporis923 inventore ',
		price: 99999,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 32,
		peopleInterested: {},
	},
	{
		streetAddress: 'prenum 4psam a liber blan8tii123123s placeat ',
		price: 12122,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 20,
		peopleInterested: {},
	},
	{
		streetAddress: 'simi3ue sed fug9iat hic ea aper12am 1iure ',
		price: 23232,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 31,
		peopleInterested: {},
	},
	{
		streetAddress: 'sunt, placeat ame2t paiatur, ani123123mi eveniet',
		price: 34343,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 30,
		peopleInterested: {},
	},
	{
		streetAddress: 'cupate del8ti lasam a13ime ducimus!',
		price: 45454,
		bedrooms: 1,
		bathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 23,
		peopleInterested: {},
	},
]

export default DUMMY_DATA2
